# Generated by Django 5.1.3 on 2024-12-01 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='books/')),
                ('description', models.TextField()),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('page_count', models.PositiveIntegerField()),
                ('cover_type', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=13)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.category')),
            ],
        ),
    ]
